import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

/**
 * The 14-clause field set from the MVP spec, Section 4.1 (based on what
 * Namibian practice treats as an essential residential lease). This is the
 * ONLY template at MVP — spec Section 4.2 is explicit that lease text must
 * be template-based, never freely generated by an LLM, and that this
 * template needs sign-off from a practicing Namibian attorney before any
 * real lease is issued through it. Nothing here should be treated as
 * legal advice.
 */
export interface LeaseFields {
  landlordName: string;
  landlordAddress: string;
  tenantName: string;
  tenantAddress: string;
  propertyDescription: string;
  rentAmount: number;
  rentEscalationPct: number | null;
  additionalCosts: string;
  paymentFrequency: string;
  depositAmount: number; // spec flags the deposit-cap rule as unverified — see SECURITY.md
  leaseStartDate: string;
  leaseEndDate: string;
  conditionNotes: string;
  maintenanceSplit: string;
  restorationObligations: string;
  terminationNoticeDays: number; // default suggestion 90 (~3 months) — editable, not a legal certainty
  usageRules: string;
  sublettingAllowed: "allowed" | "not_allowed" | "landlord_consent_required";
  furnitureAddendum: string | null;
}

function wrapText(text: string, maxCharsPerLine: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if ((current + " " + word).trim().length > maxCharsPerLine) {
      if (current) lines.push(current.trim());
      current = word;
    } else {
      current = (current + " " + word).trim();
    }
  }
  if (current) lines.push(current);
  return lines;
}

/** Renders a LeaseFields snapshot to a PDF byte array. */
export async function generateLeasePdf(fields: LeaseFields): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([595, 842]); // A4
  let y = 800;
  const marginX = 50;
  const lineHeight = 16;

  const ensureSpace = (linesNeeded: number) => {
    if (y - linesNeeded * lineHeight < 60) {
      page = doc.addPage([595, 842]);
      y = 800;
    }
  };

  const heading = (text: string) => {
    ensureSpace(2);
    page.drawText(text, { x: marginX, y, size: 13, font: boldFont, color: rgb(0.12, 0.23, 0.37) });
    y -= lineHeight * 1.5;
  };

  const paragraph = (text: string) => {
    const lines = wrapText(text, 90);
    ensureSpace(lines.length);
    for (const line of lines) {
      page.drawText(line, { x: marginX, y, size: 10, font, color: rgb(0, 0, 0) });
      y -= lineHeight;
    }
    y -= lineHeight * 0.5;
  };

  page.drawText("RESIDENTIAL LEASE AGREEMENT", {
    x: marginX,
    y,
    size: 18,
    font: boldFont,
    color: rgb(0.12, 0.23, 0.37),
  });
  y -= lineHeight * 2;

  paragraph(
    "DRAFT — generated by [PLATFORM NAME]. This template has not yet been reviewed by a " +
      "Namibian attorney (see SECURITY.md). Do not rely on this document until that review is complete."
  );

  heading("1. Parties");
  paragraph(`Landlord: ${fields.landlordName}, ${fields.landlordAddress}`);
  paragraph(`Tenant: ${fields.tenantName}, ${fields.tenantAddress}`);

  heading("2. Property");
  paragraph(fields.propertyDescription);

  heading("3. Rent, Payment & Escalation");
  paragraph(
    `Rent: N$${fields.rentAmount.toLocaleString()} per ${fields.paymentFrequency}.` +
      (fields.rentEscalationPct
        ? ` Annual escalation: ${fields.rentEscalationPct}%.`
        : " No escalation clause.")
  );

  heading("4. Additional Tenant-Responsible Costs");
  paragraph(fields.additionalCosts || "None specified.");

  heading("5. Deposit");
  paragraph(
    `Deposit: N$${fields.depositAmount.toLocaleString()}. NOTE: Namibian sources disagree on the ` +
      "statutory deposit cap for residential leases — confirm the applicable rule with your attorney " +
      "before relying on this figure (see spec Section 4.1)."
  );

  heading("6. Lease Period");
  paragraph(`From ${fields.leaseStartDate} to ${fields.leaseEndDate}.`);

  heading("7. Property Condition at Move-In");
  paragraph(fields.conditionNotes || "No condition notes recorded.");

  heading("8. Maintenance Responsibility");
  paragraph(fields.maintenanceSplit || "Not specified.");

  heading("9. Restoration Obligations at Lease End");
  paragraph(fields.restorationObligations || "Not specified.");

  heading("10. Termination Notice");
  paragraph(
    `${fields.terminationNoticeDays} days' written notice required to terminate a periodic tenancy. ` +
      "This is a suggested default, not a confirmed statutory minimum — confirm with your attorney."
  );

  heading("11. Use of Premises");
  paragraph(fields.usageRules || "Residential use only; no business use without written consent.");

  heading("12. Subletting & Cession");
  paragraph(
    fields.sublettingAllowed === "allowed"
      ? "Subletting is permitted."
      : fields.sublettingAllowed === "not_allowed"
        ? "Subletting is not permitted."
        : "Subletting requires the landlord's prior written consent."
  );

  if (fields.furnitureAddendum) {
    heading("13. Furniture Addendum");
    paragraph(fields.furnitureAddendum);
  }

  heading("14. Signatures");
  paragraph(
    "This document is signed electronically. Each signature page records the signer's typed name, " +
      "IP address, timestamp, and explicit consent — see the Lease Signatures section of the app."
  );

  return doc.save();
}
